version: '3'

services:
  # react-app:
  #   build:
  #     context: ./path/to/react/app
  #   ports:
  #     - "3000:80" # Map host port 3000 to container port 80
  #   networks:
  #     - mynetwork

  flask-app:
    build:
      context: .
    ports:
      - "5000:8000" # Map host port 5000 to container port 8000
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
