version: '3'

services:
  react-app:
    image: code_visualizer_frontend_image
    ports:
      - "9000:80" # Map host port 3000 to container port 80
    networks:
      - mynetwork

  flask-app:
    build:
      context: .
    ports:
      - "5001:8000" # Map host port 5000 to container port 8000
    networks:
      - mynetwork
    volumes:
      - ./test_project:/app/test_project

networks:
  mynetwork:
    driver: bridge
